name: Deploy site

on:
  workflow_dispatch:

jobs:
  build:
    # available images: https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
      - uses: actions/configure-pages@v5
        id: pages
      - uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: "_config.yml"
          changes: |
            {
              "url": "${{ steps.pages.outputs.origin }}",
              "baseurl": "${{ steps.pages.outputs.base_path }}"
            }
          commitChange: false
      - name: Install
        run: |
          pip3 install --upgrade jupyter
      - name: Build
        run: |
          bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      - name: Purge unused CSS 🧹
        run: |
          npm install -g purgecss
          purgecss -c purgecss.config.js
      - uses: actions/upload-pages-artifact@v3

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
